config/routes.rb
Rails.application.routes.draw do

  root 'flights#index'
  get  'flights/index'
  resources :bookings, only: [:new, :create, :show]

end

app/models/airport.rb
class Airport < ActiveRecord::Base
	validates :airport_code, presence: true, uniqueness: true
	has_many :departing_flights, class_name: "Flight", 
															 foreign_key: "from_airport_id"
	has_many :arriving_flights,  class_name: "Flight", 
															 foreign_key: "to_airport_id"
end

app/models/booking.rb
class Booking < ActiveRecord::Base
	belongs_to :flight
	has_many :tickets
	has_many :passengers, through: :tickets
	accepts_nested_attributes_for :passengers
end

app/models/flight.rb
class Flight < ActiveRecord::Base
	validates :from_airport, presence: true
	validates :to_airport,   presence: true
	validates :depart_at,    presence: true
	validates :duration, 		 presence: true

	belongs_to :from_airport, class_name: "Airport"
	belongs_to :to_airport,   class_name: "Airport"
	has_many :bookings
	has_many :passengers, through: :bookings

	def self.get_dates
		order('depart_at asc').pluck(:depart_at)
					.map { |d| [ d.strftime("%m/%d/%Y"), d.to_date ] }.uniq
	end

	def date_formatted
		depart_at.strftime("%m/%d/%Y")
	end

	def self.search(params)
		if params[:search] && !params[:date].blank?
			date = params[:date].to_date
			Flight.where(to_airport_id: params[:to], from_airport_id: params[:from],
  							 	 depart_at: date.beginning_of_day..date.end_of_day)
									 .includes(:from_airport, :to_airport)
    else
    	Flight.none
    end
	end
end

app/models/passenger.rb
class Passenger < ActiveRecord::Base
	validates :name, presence: true
	has_many :tickets
	has_many :bookings, through: :tickets
	has_many :flights, through: :bookings
end

app/models/ticket.rb
class Ticket < ActiveRecord::Base
	belongs_to :passenger
	belongs_to :booking
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def new
  	@flight = Flight.find(params[:flight_id])
  	@booking = @flight.bookings.build
  	
  	params[:passengers].to_i.times { @booking.passengers.build }
  	@booking.passengers.build if params[:passengers].blank?  		
  end

  def create
  	@booking = Booking.new(booking_params)
  	
  	if @booking.save
  		redirect_to booking_path(@booking)
  	else
  		render :new
  	end
  end

  def show
  	@booking = Booking.find(params[:id])
  end
  
  private
  
  	def booking_params
  		params.require(:booking).permit(:flight_id,
  														 passengers_attributes: [:name])
  	end
end

app/controllers/flights_controller.rb
class FlightsController < ApplicationController
  def index
  	@airports = Airport.all.pluck(:airport_code, :id).sort
  	@dates = Flight.get_dates
  	@passengers = 1..4
  	@flights = Flight.search(params)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/flights_helper.rb
module FlightsHelper
end

app/views/bookings/new.html.erb
<p>ID: <%= @flight.id %></p>
<p>
  From: <%= @flight.from_airport.airport_code %><br>
	To: <%= @flight.to_airport.airport_code %><br>
	Date: <%= @flight.depart_at %><br>
	Duration: <%= distance_of_time_in_words(@flight.duration) %><br>
</p>

<%= form_for @booking do |f| %>
	<%= f.hidden_field :flight_id %>
	
	<h3>Passenger Information</h3>
	<div>
		<%= f.fields_for :passengers do |p| %>
			<div>
				<%= p.label :name %>
				<%= p.text_field :name %>			
			</div>
		<% end %>
	</div>
	<%= f.submit "Book flight" %>
<% end %>

app/views/bookings/show.html.erb
<div>
	<h3>Flight ID: <%= @booking.flight.id %></h3>
	<p>
		From: 		<%= @booking.flight.to_airport.airport_code %><br>
		To: 			<%= @booking.flight.from_airport.airport_code %><br>
		Date: 		<%= @booking.flight.depart_at %><br>
		Duration: <%= distance_of_time_in_words(@booking.flight.duration) %><br>
	</p>
	<h3>Passenger Information</h3>
	<p>
		<% @booking.passengers.each do |p| %>
			Name: <%= p.name %><br>
		<% end %>
	</p>
</div>
	
	
		

app/views/flights/index.html.erb
<h1>Flights</h1>

<div class="search_form">
	<%= render 'shared/search_form' %>
</div>
<div class="search_results">
	<% if @flights.any? %>
		<%= render 'shared/search_results' %>
	<% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FlightBooker</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>
<p><%= debug(params) if Rails.env.development? %></p>

</body>
</html>

app/views/shared/_search_form.html.erb
<%= form_tag flights_index_path, method: 'get' do %>
	<div class="row">
		<%= hidden_field_tag :search %>

		<div>
			<%= select_tag :from, options_for_select(@airports), prompt: "From" %>
		</div>

		<div>
			<%= select_tag :to, options_for_select(@airports), prompt: "To" %>
		</div>

		<div>
			<%= select_tag :passengers, options_for_select(@passengers), 
										 prompt: "# of passengers" %>
		</div>

		<div>
			<%= select_tag :date, options_for_select(@dates), prompt: "Date" %>
		</div>

		<div>
			<%= submit_tag "Search", name: nil, class: "button" %>
		</div>
	</div>
<% end %>

app/views/shared/_search_results.html.erb
<%= form_tag new_booking_path, method: :get do %>
	<table>
		<thead>
			<tr>
				<th>Select</th>
				<th>Flight</th>
				<th>Date</th>
				<th>Departs</th>
				<th>From</th>
				<th>To</th>
				<th>Duration</th>
			</tr>
		</thead>

		<div class="search_results">
			<tbody>
				<% @flights.each do |flight| %>
				<tr>
					<td><%= radio_button_tag :flight_id, flight.id %></td>
					<td><%= flight.id %></td>
					<td><%= flight.depart_at.strftime("%B %d, %Y") %></td>
					<td><%= flight.depart_at.strftime("%I:%M %p") %></td>
					<td><%= flight.from_airport.airport_code %></td>
					<td><%= flight.to_airport.airport_code %></td>
					<td><%= distance_of_time_in_words(flight.duration) %></td>
				</tr>
				<% end %>
			</tbody>
		</div>
	</table>
	<%= submit_tag "Select Flight", name: nil, class: "button" %>
	<%= hidden_field_tag :passengers, params[:passengers] %>
<% end %>